backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow
media_folder: static/images/cms
public_folder: /images/cms

display_url: https://ourlifeloop.com

collections:
  - name: blog
    label: Blog
    folder: src/cms/blog
    preview_path: 'blog/{{slug}}'
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - name: type
        label: Type
        widget: select
        options:
          - { label: Customer Spotlight, value: spotlight }
          - { label: News, value: news }
          - { label: Industry Insights, value: insights }
          - { label: Case Studies, value: studies }
      - { name: author, label: Author }
      - { name: title, label: Title }
      - { name: photo, label: Photo, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: careers
    label: Careers
    folder: src/cms/careers
    preview_path: 'career/{{slug}}'
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - name: responsibilities
        label: Responsibilities
        widget: list
        field: { label: Responsibility, name: responsibility }
      - { name: body, label: Body, widget: markdown }

  - name: testimonials
    label: Testimonials
    folder: src/cms/testimonials
    slug: '{{author}}_{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}'
    create: true
    fields:
      - { name: logo, label: Logo, widget: image }
      - { name: quote, label: Quote }
      - { name: author, label: Author }
      - { name: position, label: Position, required: false }
      - name: pages
        label: Page(s)
        widget: select
        multiple: true
        options:
          - { label: Home Page, value: / }
          - { label: Covid, value: /covid }
          - { label: Senior Living Solution, value: /solutions/senior-living }
          - { label: AIDD Solution, value: /solutions/aidd }
          - {
              label: Specialized Services Solution,
              value: /solutions/specialized-services,
            }
          - { label: Communication Feature, value: /features/communication }
          - {
              label: Calendar Management Feature,
              value: /features/calendar-management,
            }
          - { label: Designer Feature, value: /features/designer }
          - { label: Digital Signage Feature, value: /features/displays }
          - {
              label: Resident Tracking Feature,
              value: /features/resident-tracking,
            }
          - {
              label: Connection Portal Feature,
              value: /features/connection-portal,
            }
          - { label: Photo & Video Sharing Feature, value: /features/photos }
          - { label: Resident Portal Feature, value: /features/resident-portal }
          - { label: Transportation Feature, value: /features/transportation }
          - { label: Work Requests Feature, value: /features/maintenance }

  - name: training-videos
    label: Training Videos
    folder: src/cms/training-videos
    create: true
    fields:
      - { name: title, label: Title }
      - { name: video, label: Video URL }
      - { name: cover, label: Cover Photo, widget: image }
      - name: isNew
        label: Is New
        widget: boolean
        required: false
        default: false
      - name: isMobile
        label: Is Mobile
        widget: boolean
        required: false
        default: false
      - name: topics
        label: Topics
        widget: select
        multiple: true
        options:
          - { label: Activity Calendar, value: activity-calendar }
          - { label: Activity Feed, value: activity-feed }
          - { label: Communication, value: messaging }
          - { label: Connection Management, value: connection-management }
          - { label: Connection Portal, value: connection-portal }
          - { label: Designer, value: designer }
          - { label: Displays, value: displays }
          - { label: Getting Started, value: getting-started }
          - { label: LifeLoop Learning Courses, value: learning-courses }
          - { label: Work Requests, value: work-requests }
          - { label: Marketing, value: marketing }
          - { label: Photos, value: photos }
          - { label: Reporting, value: reporting }
          - { label: Resident Engagement Tools, value: resident-engagement }
          - { label: Resident Management, value: resident-management }
          - { label: Resident Portal, value: resident-portal }
          - { label: Transportation, value: transportation }
          - { label: Staff Management, value: staff-management }
      - name: userTypes
        label: User Types
        widget: select
        multiple: true
        options:
          - { label: Staff Member, value: staff }
          - { label: Connection, value: connection }
          - { label: Resident, value: resident }

  - name: training-documents
    label: Training Documents
    folder: src/cms/training-documents
    create: true
    fields:
      - { name: title, label: Title }
      - { name: document, label: Document, widget: file }
      - name: isMobile
        label: Is Mobile
        widget: boolean
        required: false
        default: false
      - name: topics
        label: Topics
        widget: select
        multiple: true
        options:
          - { label: Activity Calendar, value: activity-calendar }
          - { label: Activity Feed, value: activity-feed }
          - { label: Communication, value: messaging }
          - { label: Connection Management, value: connection-management }
          - { label: Connection Portal, value: connection-portal }
          - { label: Designer, value: designer }
          - { label: Displays, value: displays }
          - { label: Getting Started, value: getting-started }
          - { label: LifeLoop Learning Courses, value: learning-courses }
          - { label: Work Requests, value: work-requests }
          - { label: Marketing, value: marketing }
          - { label: Photos, value: photos }
          - { label: Reporting, value: reporting }
          - { label: Resident Engagement Tools, value: resident-engagement }
          - { label: Resident Management, value: resident-management }
          - { label: Resident Portal, value: resident-portal }
          - { label: Transportation, value: transportation }
          - { label: Staff Management, value: staff-management }
      - name: userTypes
        label: User Types
        widget: select
        multiple: true
        options:
          - { label: Staff Member, value: staff }
          - { label: Connection, value: connection }
          - { label: Resident, value: resident }

  - name: training-faqs
    label: Training FAQs
    folder: src/cms/training-faqs
    create: true
    identifier_field: question
    fields:
      - { name: question, label: Question }
      - { name: answer, label: Answer, widget: text }
      - name: isMobile
        label: Is Mobile
        widget: boolean
        required: false
        default: false
      - name: topics
        label: Topics
        widget: select
        multiple: true
        options:
          - { label: Main Page, value: main-page }
          - { label: Activity Calendar, value: activity-calendar }
          - { label: Activity Feed, value: activity-feed }
          - { label: Communication, value: messaging }
          - { label: Connection Management, value: connection-management }
          - { label: Connection Portal, value: connection-portal }
          - { label: Designer, value: designer }
          - { label: Displays, value: displays }
          - { label: Getting Started, value: getting-started }
          - { label: LifeLoop Learning Courses, value: learning-courses }
          - { label: Work Requests, value: work-requests }
          - { label: Marketing, value: marketing }
          - { label: Photos, value: photos }
          - { label: Reporting, value: reporting }
          - { label: Resident Engagement Tools, value: resident-engagement }
          - { label: Resident Management, value: resident-management }
          - { label: Resident Portal, value: resident-portal }
          - { label: Transportation, value: transportation }
          - { label: Staff Management, value: staff-management }
      - name: userTypes
        label: User Types
        widget: select
        multiple: true
        options:
          - { label: Staff Member, value: staff }
          - { label: Connection, value: connection }
          - { label: Resident, value: resident }
