backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/images/cms
public_folder: /images

display_url: https://ourlifeloop.netlify.com/

collections:
  - name: blog
    label: Blog
    folder: src/cms/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - name: type
        label: Type
        widget: select
        options:
          - { label: Customer Spotlight, value: spotlight }
          - { label: News, value: news }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
