backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow
media_folder: static/images/cms
public_folder: /images/cms

display_url: https://ourlifeloop.netlify.com/

collections:
  - name: blog
    label: Blog
    folder: src/cms/blog
    preview_path: 'blog/{{slug}}'
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - name: type
        label: Type
        widget: select
        options:
          - { label: Customer Spotlight, value: spotlight }
          - { label: News, value: news }
          - { label: Industry Insights, value: insights }
          - { label: Case Studies, value: studies }
      - { name: author, label: Author }
      - { name: title, label: Title }
      - { name: photo, label: Photo, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: training-videos
    label: Training Videos
    folder: src/cms/training-videos
    create: true
    fields:
      - { name: title, label: Title }
      - { name: video, label: Video URL }
      - { name: cover, label: Cover Photo, widget: image }
      - name: isNew
        label: Is New
        widget: boolean
        required: false
        default: false
      - name: isMobile
        label: Is Mobile
        widget: boolean
        required: false
        default: false
      - name: topics
        label: Topics
        widget: select
        multiple: true
        options:
          - { label: Getting Started, value: getting-started }
          - { label: Activity Calendar, value: activity-calendar }
          - { label: Resident Management, value: resident-management }
          - { label: Photos, value: photos }
          - { label: Messaging, value: messaging }
          - { label: Maintenance, value: maintenance }
          - { label: Transportation, value: transportation }
          - { label: Displays, value: displays }
          - { label: Resident Portal, value: resident-portal }
          - { label: Family Portal, value: family-portal }
          - { label: Staff Management, value: staff-management }
          - { label: Reporting, value: reporting }
          - { label: Calendar Designer, value: calendar-designer }
          - { label: Connections, value: connections }
          - { label: Marketing, value: marketing }
      - name: userTypes
        label: User Types
        widget: select
        multiple: true
        options:
          - { label: Staff Member, value: staff }
          - { label: Family Member, value: family }
          - { label: Resident, value: resident }

  - name: training-documents
    label: Training Documents
    folder: src/cms/training-documents
    create: true
    fields:
      - { name: title, label: Title }
      - { name: document, label: Document, widget: file }
      - name: isMobile
        label: Is Mobile
        widget: boolean
        required: false
        default: false
      - name: topics
        label: Topics
        widget: select
        multiple: true
        options:
          - { label: Getting Started, value: getting-started }
          - { label: Activity Calendar, value: activity-calendar }
          - { label: Resident Management, value: resident-management }
          - { label: Photos, value: photos }
          - { label: Messaging, value: messaging }
          - { label: Maintenance, value: maintenance }
          - { label: Transportation, value: transportation }
          - { label: Displays, value: displays }
          - { label: Resident Portal, value: resident-portal }
          - { label: Family Portal, value: family-portal }
          - { label: Staff Management, value: staff-management }
          - { label: Reporting, value: reporting }
          - { label: Calendar Designer, value: calendar-designer }
          - { label: Connections, value: connections }
          - { label: Marketing, value: marketing }
      - name: userTypes
        label: User Types
        widget: select
        multiple: true
        options:
          - { label: Staff Member, value: staff }
          - { label: Family Member, value: family }
          - { label: Resident, value: resident }

  - name: training-faqs
    label: Training FAQs
    folder: src/cms/training-faqs
    create: true
    identifier_field: question
    fields:
      - { name: question, label: Question }
      - { name: answer, label: Answer, widget: text }
      - name: isMobile
        label: Is Mobile
        widget: boolean
        required: false
        default: false
      - name: topics
        label: Topics
        widget: select
        multiple: true
        options:
          - { label: Main Page, value: main-page }
          - { label: Getting Started, value: getting-started }
          - { label: Activity Calendar, value: activity-calendar }
          - { label: Resident Management, value: resident-management }
          - { label: Photos, value: photos }
          - { label: Messaging, value: messaging }
          - { label: Maintenance, value: maintenance }
          - { label: Transportation, value: transportation }
          - { label: Displays, value: displays }
          - { label: Resident Portal, value: resident-portal }
          - { label: Family Portal, value: family-portal }
          - { label: Staff Management, value: staff-management }
          - { label: Reporting, value: reporting }
          - { label: Calendar Designer, value: calendar-designer }
          - { label: Connections, value: connections }
          - { label: Marketing, value: marketing }
      - name: userTypes
        label: User Types
        widget: select
        multiple: true
        options:
          - { label: Staff Member, value: staff }
          - { label: Family Member, value: family }
          - { label: Resident, value: resident }
