backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/images/cms
public_folder: /images/cms

display_url: https://ourlifeloop.netlify.com/

collections:
  - name: blog
    label: Blog
    folder: src/cms/blog
    preview_path: 'blog/{{slug}}'
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - name: type
        label: Type
        widget: select
        options:
          - { label: Customer Spotlight, value: spotlight }
          - { label: News, value: news }
          - { label: Industry Insights, value: insights }
      - { name: author, label: Author }
      - { name: title, label: Title }
      - { name: photo, label: Photo, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
